[package]
name = "delivery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.2"
env_logger = "0.6"
base64 = "0.12.1"
json = "*"